org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.23
forge_version_range=[47.4,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=createinfinitespeed
mod_name=Create Infinite Speed
mod_license=MIT
mod_version=0.2.0
mod_group_id=jp.taitai.createinfinitespeed
mod_authors=たいたい
mod_description=Create addon prototype with finite and practically-unlimited speed controllers.
create_version=6.0.8
create_file_id=7178761
